import type { ReactNode } from 'react'

/**
 * GENERATED by scripts/import-drowning-art.ts — do not edit by hand.
 * Run `pnpm drowning:art` after changing anything in ./art/figure/.
 *
 * Hand-drawn replacements for the figure's parts, keyed by the ids in
 * PART_LIST. Figure prefers these; parts with no entry keep their built-in
 * drawing, so the figure can be replaced a piece at a time.
 */
export const HAND_DRAWN_PARTS: Record<string, ReactNode> = {
    'arm-l-crimped': (
        <>
                <defs
                id="arm-l-crimped-defs1" />

                <path
                style={{"fill": 'none', "stroke": 'currentColor', "strokeWidth": '2.4', "strokeLinecap": 'round', "strokeLinejoin": 'round'}}
                d="M 26.245073,26.0497 16.867181,20.188518 15.890317,26.50557 11.917738,24.030848"
                id="arm-l-crimped-path2" />
        </>
    ),
    'arm-l': (
        <>
                <path d="M26 26l-14-9" fill="none" stroke="currentColor" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round"/>
        </>
    ),
    'arm-r-stub': (
        <>
                <defs
                id="arm-r-stub-defs2" />

                <path
                style={{"fill": 'none', "stroke": 'currentColor', "strokeWidth": '2.4', "strokeLinecap": 'round', "strokeLinejoin": 'round'}}
                d="m 25.984576,26.179949 6.121679,-4.167952"
                id="arm-r-stub-path3" />
                <path
                style={{"fill": 'none', "stroke": 'currentColor', "strokeWidth": '1.1', "strokeLinecap": 'round', "strokeLinejoin": 'round'}}
                d="m 31.064267,21.816624 -0.06512,-3.972579"
                id="arm-r-stub-path4" />
                <path
                style={{"fill": 'none', "stroke": 'currentColor', "strokeWidth": '1.5', "strokeLinecap": 'round', "strokeLinejoin": 'round'}}
                d="m 31.780634,22.793487 4.493573,2.930591"
                id="arm-r-stub-path5" />
        </>
    ),
    'arm-r': (
        <>
                <path d="M26 26l14-9" fill="none" stroke="currentColor" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round"/>
        </>
    ),
    'drips': (
        <>
                <g fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round"><path d="M20 50v4M31 44v3M27 55v5"/></g>
        </>
    ),
    'head-dead': (
        <>
                <g fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round"><path d="M21.5 10.5l3 3M24.5 10.5l-3 3"/><path d="M27.5 10.5l3 3M30.5 10.5l-3 3"/></g>
        </>
    ),
    'head': (
        <>
                <circle cx="26" cy="13" r="8" fill="none" stroke="currentColor" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round"/>
        </>
    ),
    'hole': (
        <>
                <circle cx="26" cy="33" r="2.6" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round"/>
        </>
    ),
    'leg-l-serrated': (
        <>
                <defs
                id="leg-l-serrated-defs1" />

                <path
                style={{"fill": 'none', "stroke": 'currentColor', "strokeWidth": '2.4', "strokeLinecap": 'round', "strokeLinejoin": 'round', "strokeOpacity": '1'}}
                d="m 26.114824,46.628963 -3.84233,7.619537 3.516709,2.474722 -7.098543,3.777206 3.191088,5.470437 -5.20994,3.06084"
                id="leg-l-serrated-path4" />
        </>
    ),
    'leg-l': (
        <>
                <path d="M26 47L17 69" fill="none" stroke="currentColor" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round"/>
        </>
    ),
    'leg-r': (
        <>
                <path d="M26 47L36 68" fill="none" stroke="currentColor" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round"/>
        </>
    ),
    'spines': (
        <>
                <g fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round"><path d="M22 57l-6-3M23 61l-6-1M24 65l-5 1"/></g>
        </>
    ),
    'torso-bent': (
        <>
                <path d="M26 21c-4 7 4 17 0 26" fill="none" stroke="currentColor" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round"/>
        </>
    ),
    'torso-split': (
        <>
                <path d="M26 21c-4 6 3 11 1 15" fill="none" stroke="currentColor" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round"/><path d="M30 39c-3 5 0 4-2 8" fill="none" stroke="currentColor" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round"/>
        </>
    ),
    'torso': (
        <>
                <path d="M26 21v26" fill="none" stroke="currentColor" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round"/>
        </>
    ),
    'welts': (
        <>
                <g fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round"><circle cx="20" cy="31" r="1.6"/><circle cx="32" cy="37" r="1.3"/><circle cx="22" cy="42" r="1.1"/></g>
        </>
    )
}
